server:
  port: 8080
  servlet:
    context-path: /ecommerce


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce_project
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: 123456789
  jpa:
    hibernate:
      ddl-auto: update
      show sql: true


jwt:
  signerKey: "nUfJ0IIEZWvOFqlud2hLrdVgGkYLYNH6JR6NkF6bAMq+yhdoQrah87JcbUsnXzQ4"
  valid-duration: 3600 #in second
  refreshable-duration: 36000 # in second


